apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  labels:
    app: backend
spec:
  replicas: 5
  selector:
    matchLabels:
      app: backend
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: backend
    spec:
# You need this only if you want to fetch a private image
#      imagePullSecrets:
#        - name: regcred
      restartPolicy: Always
      containers:
        - image: zenstok/scalable-chat-app-example-backend:amd64
          name: scalable-chat-app-example-backend
          ports:
            - containerPort: 3000
# Control resources used for pods using a config like this (make sure cluster has sufficient resources)
#          resources:
#            limits:
#              cpu: "1000m"    # Maximum CPU limit
#              memory: "1Gi"   # Maximum memory limit
#            requests:
#              cpu: "1000m"    # Minimum CPU request
#              memory: "1Gi"   # Minimum memory request
          readinessProbe:
            httpGet:
              path: "/health"
              port: 3000
            initialDelaySeconds: 10
            timeoutSeconds: 5
          env:
            - name: REDIS_HOST
              value: "redis-service"
            - name: REDIS_PORT
              value: "6379"
            - name: DB_HOST
              value: "postgres-service"
            - name: DB_PORT
              value: "5432"
            - name: DB_USERNAME
              value: "username"
            - name: DB_PASSWORD
              value: "password"
            - name: DB_NAME
              value: "dbname"
            - name: DB_TIMEZONE
              value: "UTC"