apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  labels:
    app: backend
spec:
  replicas: 5
  selector:
    matchLabels:
      app: backend
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: backend
    spec:
      restartPolicy: Always
      containers:
        - image: zenstok/scalable-chat-app-example-backend
          name: scalable-chat-app-example-backend
          ports:
            - containerPort: 3000
          env:
            - name: REDIS_HOST
              value: "redis-service"
            - name: REDIS_PORT
              value: "6379"
            - name: DB_HOST
              value: "postgres-service"
            - name: DB_PORT
              value: "5432"
            - name: DB_USERNAME
              value: "username"
            - name: DB_PASSWORD
              value: "password"
            - name: DB_NAME
              value: "dbname"
            - name: DB_TIMEZONE
              value: "UTC"